site_name: My Docs
site_url: https://e-racingbergamo.github.io/documentation
theme:
  name: material
  # features:
  #   - katex
  favicon: assets/images/simbolo_blu.ico
  logo: assets/images/simbolo_blu.ico
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Passa al tema scuro
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passa al tema chiaro

plugins:
  - search    # Mantiene la ricerca (importante!)
  - callouts  # Abilita il supporto a > [!note] di Obsidian

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details      
  - pymdownx.superfences
  # - pymdownx.blocks.admonition

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.15.0/dist/katex.min.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Codice:
      - Lezioni di C:
          - Sintassi di base: codice/lezioni_di_c/sintassi_base_c.md
          - Standard int: codice/lezioni_di_c/stdint.md
          - Visibilità e durata delle variabili: codice/lezioni_di_c/visibilità_delle_variabili.md
          - Strutture di controllo: codice/lezioni_di_c/strutture_controllo.md
          - Strutture dati di base: codice/lezioni_di_c/strutture_base.md
          - Funzioni: codice/lezioni_di_c/funzioni.md
          - Puntatori: codice/lezioni_di_c/puntatori.md
          - Strutture dati:
              - Strutture dinamiche: codice/lezioni_di_c/strutture_dati/strutture_dinamiche.md
              - Linked list: codice/lezioni_di_c/strutture_dati/linked_list.md
              - Binary tree: codice/lezioni_di_c/strutture_dati/binary_tree.md
      - Centralina: codice/centralina.md
  - Hardware:
      - Inverter:
          - Gestione termica: hardware/inverter/gestione_termica.md
      - Centralina FAE:
          - ADC: hardware/centralina_fae/adc.md
      - Batteria:
          - State Of Charge (SOC): hardware/battery/SOC.md
  # - Hardware:
  #     - Panoramica hardware: hardware/panoramica_hardware.md
  #     - Schede elettroniche: hardware/schede_elettroniche.md
  #     - Sensori e attuatori: hardware/sensori_attuatori.md
  # - Risorse utili:
  #     - Strumenti software: risorse_utili/strumenti_software.md
  #     - Stile di codice: risorse_utili/stile_di_codice.md
  #     - Git e GitHub: risorse_utili/git_github.md
  #     - Link utili: risorse_utili/link_utili.md